### ISSUE TITLE
Server error from POST to resources endpoint

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#145]
Run `test_app/scripts/bootstrap.sh`, as admin user

POST http://127.0.0.1:8000/api/v1/service-index/resources/

```json
{
    "ansible_id": "4c4b92fe:efc2135c-cb85-4847-87b7-af00373701d5",
    "resource_type": "shared.user",
    "resource_data": {"username": "george"}
}
```

where this `ansible_id` doesn't exist in the system yet.

Expected: Adds user george

Actual: 500

```
Internal Server Error: /api/v1/service-index/resources/
Traceback (most recent call last):
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/testing/django-ansible-base/ansible_base/resource_registry/serializers.py", line 86, in create
    return Resource.create_resource(r_type, validated_data["resource_data"], ansible_id=validated_data.get("ansible_id"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/testing/django-ansible-base/ansible_base/resource_registry/models/resource.py", line 118, in create_resource
    resource = cls.objects.get(object_id=content_object.pk, content_type=c_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
ansible_base.resource_registry.models.resource.Resource.DoesNotExist: Resource matching query does not exist.
[15/Feb/2024 21:41:25] "POST /api/v1/service-index/resources/ HTTP/1.1" 500 132410
```

**Comment by AlanCoding** [comment]
Seems that POST has been disabled for this endpoint.
