### ISSUE TITLE
DELETE to resource id endpoint gives 500

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#147]
Expected: anything other than 500?

```
Internal Server Error: /api/v1/service-index/resources/4c4b92fe:efc2135c-cb85-4847-87b7-af00373701d5/
Traceback (most recent call last):
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/backends/base/base.py", line 313, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/home/alancoding/repos/awx/testing/django-ansible-base/ansible_base/resource_registry/views.py", line 57, in perform_destroy
    instance.delete_resource()
  File "/home/alancoding/repos/awx/testing/django-ansible-base/ansible_base/resource_registry/models/resource.py", line 101, in delete_resource
    with transaction.atomic():
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/transaction.py", line 263, in __exit__
    connection.commit()
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/backends/base/base.py", line 337, in commit
    self._commit()
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/backends/base/base.py", line 312, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/alancoding/repos/awx/env/lib64/python3.11/site-packages/django/db/backends/base/base.py", line 313, in _commit
    return self.connection.commit()
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
[15/Feb/2024 22:00:46] "DELETE /api/v1/service-index/resources/4c4b92fe:efc2135c-cb85-4847-87b7-af00373701d5/ HTTP/1.1" 500 139867
```

Ping @newswangerd @rochacbruno for info.

**Comment by AlanCoding** [comment]
Ran `./test_app/scripts/bootstrap.sh`

DELETE http://127.0.0.1:8000/api/v1/service-index/resources/293c7023-ec36-4ae1-ad09-5ad59240a26e/

That seems to work now, so I'll close this.
