### ISSUE TITLE
Can't run DAB without the resource registr app

### ISSUE THREAD

**Issue by newswangerd** [ansible/django-ansible-base#432]
### Bug Summary

After this commit: https://github.com/ansible/django-ansible-base/commit/b8edc8cf928b6b056589c4c1145b2c3149eb1047 I'm getting the following error in Hub, which doesn't currently enable the resource registry.

```
pulp-1          | Traceback (most recent call last):
pulp-1          |   File "/nginx/template_nginx.py", line 26, in <module>
pulp-1          |     django.setup()
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
pulp-1          |     apps.populate(settings.INSTALLED_APPS)
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
pulp-1          |     app_config.import_models()
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
pulp-1          |     self.models_module = import_module(models_module_name)
pulp-1          |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
pulp-1          |     return _bootstrap._gcd_import(name[level:], package, level)
pulp-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
pulp-1          |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
pulp-1          |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
pulp-1          |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
pulp-1          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
pulp-1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pulp-1          |   File "/src/galaxy_ng/galaxy_ng/app/models/__init__.py", line 13, in <module>
pulp-1          |     from .organization import Organization, Team
pulp-1          |   File "/src/galaxy_ng/galaxy_ng/app/models/organization.py", line 3, in <module>
pulp-1          |     from ansible_base.lib.abstract_models import AbstractOrganization, AbstractTeam
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/abstract_models/__init__.py", line 1, in <module>
pulp-1          | Database migrated!
pulp-1          |     from .common import CommonModel, ImmutableCommonModel, NamedCommonModel, UniqueNamedCommonModel
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/abstract_models/common.py", line 14, in <module>
pulp-1          |     from ansible_base.lib.utils.models import current_user_or_system_user, is_system_user
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/utils/models.py", line 16, in <module>
pulp-1          |     from ansible_base.resource_registry.models import ResourceType
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/__init__.py", line 1, in <module>
pulp-1          |     from .resource import Resource, ResourceType, init_resource_from_object  # noqa: 401
pulp-1          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/resource.py", line 11, in <module>
pulp-1          |     from .service_identifier import service_id
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/service_identifier.py", line 6, in <module>
pulp-1          |     class ServiceID(models.Model):
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 134, in __new__
pulp-1          |     raise RuntimeError(
pulp-1          | RuntimeError: Model class ansible_base.resource_registry.models.service_identifier.ServiceID doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
pulp-1          | ready
pulp-1          | Calling /etc/init/pulpcore-api
pulp-1          | /usr/local/bin/pulpcore-api
pulp-1          | Traceback (most recent call last):
pulp-1          |   File "/usr/local/bin/pulpcore-manager", line 8, in <module>
pulp-1          |     sys.exit(manage())
pulp-1          |              ^^^^^^^^
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/pulpcore/app/manage.py", line 11, in manage
pulp-1          |     execute_from_command_line(sys.argv)
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
pulp-1          |     utility.execute()
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
pulp-1          |     django.setup()
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
pulp-1          |     apps.populate(settings.INSTALLED_APPS)
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
pulp-1          |     app_config.import_models()
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
pulp-1          |     self.models_module = import_module(models_module_name)
pulp-1          |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
pulp-1          |     return _bootstrap._gcd_import(name[level:], package, level)
pulp-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
pulp-1          |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
pulp-1          |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
pulp-1          |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
pulp-1          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
pulp-1          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
pulp-1          |   File "/src/galaxy_ng/galaxy_ng/app/models/__init__.py", line 13, in <module>
pulp-1          |     from .organization import Organization, Team
pulp-1          |   File "/src/galaxy_ng/galaxy_ng/app/models/organization.py", line 3, in <module>
pulp-1          |     from ansible_base.lib.abstract_models import AbstractOrganization, AbstractTeam
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/abstract_models/__init__.py", line 1, in <module>
pulp-1          |     from .common import CommonModel, ImmutableCommonModel, NamedCommonModel, UniqueNamedCommonModel
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/abstract_models/common.py", line 14, in <module>
pulp-1          |     from ansible_base.lib.utils.models import current_user_or_system_user, is_system_user
pulp-1          |   File "/src/django-ansible-base/ansible_base/lib/utils/models.py", line 16, in <module>
pulp-1          |     from ansible_base.resource_registry.models import ResourceType
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/__init__.py", line 1, in <module>
pulp-1          |     from .resource import Resource, ResourceType, init_resource_from_object  # noqa: 401
pulp-1          |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/resource.py", line 11, in <module>
pulp-1          |     from .service_identifier import service_id
pulp-1          |   File "/src/django-ansible-base/ansible_base/resource_registry/models/service_identifier.py", line 6, in <module>
pulp-1          |     class ServiceID(models.Model):
pulp-1          |   File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 134, in __new__
pulp-1          |     raise RuntimeError(
pulp-1          | RuntimeError: Model class ansible_base.resource_registry.models.service_identifier.ServiceID doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.****
```

**Comment by AlanCoding** [comment]
@john-westcott-iv addressed in https://github.com/ansible/django-ansible-base/pull/433
