### ISSUE TITLE
Remove model imports in any utils/ modules

### ISSUE THREAD

**Issue by AlanCoding** [ansible/django-ansible-base#443]
To prevent circular imports, we want ansible_base/utils imports to always be "safe" to import inside of Django apps.

Right now this doesn't work due to a stray import of `AbstractUser` which needs apps to be loaded before importing (or will throw an error).

This can be done by moving these imports in-line, or more elegantly, but further code refactoring.

**Comment by Kuppjaerk** [comment]
Hi!

Is this issue still awaiting resolution? If so, I'd like to take a look at it. I'm a uni student who's currently taking an open source course, which includes making contributions.

**Comment by AlanCoding** [comment]
Yes, still unresolved. The import in question is:

https://github.com/ansible/django-ansible-base/blob/5f1ca896a4dc94a4ed7f1da0dc371ddc4217669f/ansible_base/lib/utils/models.py#L9

In many cases, `Model`, would be an acceptable replacement, which does not require apps to be loaded to be able to import.

A solution can be verified by using the `python3` terminal, without doing any other setup before that.

```python
>>> from ansible_base.lib.utils import *
>>> from ansible_base.lib.utils.models import *
```

The first line is successful, but the 2nd line errors. Make that not error, and this is solved.

**Comment by Kuppjaerk** [comment]
Alright, I'll start working on this then, thanks for the quick reply! I'm quite new to contributing to ansible, is there a certain Matrix room I could ask questions regarding django-ansible-base?

**Comment by AlanCoding** [comment]
This is not fixed. Current example as a traceback:

```
Traceback (most recent call last):
  File "/home/arominge/venvs/awx/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
           ^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 342, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 167, in _multicall
    raise exception
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/helpconfig.py", line 112, in pytest_cmdline_parse
    config = yield
             ^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 1146, in pytest_cmdline_parse
    self.parse(args)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 1527, in parse
    self._preparse(args, addopts=addopts)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/config/__init__.py", line 1431, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 167, in _multicall
    raise exception
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/warnings.py", line 129, in pytest_load_initial_conftests
    return (yield)
            ^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 139, in _multicall
    teardown.throw(exception)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/_pytest/capture.py", line 173, in pytest_load_initial_conftests
    yield
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pluggy/_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pytest_django/plugin.py", line 361, in pytest_load_initial_conftests
    _setup_django(early_config)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/pytest_django/plugin.py", line 237, in _setup_django
    django.setup()
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/typeguard/_importhook.py", line 98, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/arominge/repos/django-ansible-base/ansible_base/rbac/__init__.py", line 1, in <module>
    from ansible_base.rbac.permission_registry import permission_registry
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/typeguard/_importhook.py", line 98, in exec_module
    super().exec_module(module)
  File "/home/arominge/repos/django-ansible-base/ansible_base/rbac/permission_registry.py", line 12, in <module>
    from ansible_base.lib.utils.auth import get_organization_model
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/typeguard/_importhook.py", line 98, in exec_module
    super().exec_module(module)
  File "/home/arominge/repos/django-ansible-base/ansible_base/lib/utils/auth.py", line 12, in <module>
    from ansible_base.lib.abstract_models.organization import AbstractOrganization
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/typeguard/_importhook.py", line 98, in exec_module
    super().exec_module(module)
  File "/home/arominge/repos/django-ansible-base/ansible_base/lib/abstract_models/__init__.py", line 1, in <module>
    from .common import CommonModel, ImmutableCommonModel, NamedCommonModel, UniqueNamedCommonModel
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/typeguard/_importhook.py", line 98, in exec_module
    super().exec_module(module)
  File "/home/arominge/repos/django-ansible-base/ansible_base/lib/abstract_models/common.py", line 5, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/contrib/auth/models.py", line 3, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/contrib/auth/base_user.py", line 57, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/home/arominge/venvs/awx/lib64/python3.11/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

You can see I tried to add

```
  File "/home/arominge/repos/django-ansible-base/ansible_base/rbac/permission_registry.py", line 12, in <module>
    from ansible_base.lib.utils.auth import get_organization_model
```

As the lib import should be "safe", it absolutely isn't, because of this issue.
